name             'rb-proxy'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures redborder proxy'
version          '0.2.4'

depends 'rb-common'
depends 'rb-selinux'
depends 'zookeeper'
depends 'kafka'
depends 'geoip'
depends 'snmp'
depends 'rbmonitor'
depends 'rbscanner'
depends 'f2k'
depends 'pmacct'
depends 'logstash'
depends 'rsyslog'
depends 'rbnmsp'
depends 'rbale'
depends 'n2klocd'
depends 'rb-exporter'
# depends 'freeradius'
depends 'k2http'
depends 'rbcgroup'
